apiVersion: v1
appVersion: "1.0"
description: A Helm chart for deploying the TMC prototype on Kubernetes
name: tmc-proto
version: 0.1.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
