display: ":0"
xauthority: "~/.Xauthority"

global:
  retry: 
  - "--sleep=1"
  - "--tries=100"
  sub-system:
    ska-tango-util:
      enabled: false
    ska-tango-base:
      enabled: false
    ska-webjive:
      enabled: true
  tango_host: databaseds-tango-base-test:10000
  dsconfig:
    timeout: 300s
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-dsconfig
      tag: 1.5.1
      pullPolicy: IfNotPresent
  itango:
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-itango
      tag: 9.3.5
      pullPolicy: IfNotPresent

ska-tango-base:
  enabled: false
  vnc:
    replicas: 1
    enabled: true
  tangorest:
    enabled: true
    replicas: 1
  tangodb:
    use_pv: false

ska-webjive:
  enabled: true
  minikube: false
  ingress:
    enabled: true
    nginx: true
  tangogql:
    replicas: 3
    resources:
      requests:
        cpu: 600m     # 600m = 0.6 CPU
        memory: 512Mi # 512Mi = 0.5 GB mem
      limits:
        cpu: 1000m     # 1000m = 1 CPU
        memory: 1024Mi # 1024Mi = 1 GB mem


ska-mid-cbf:
  enabled: true
  ska-tango-base: 
    enabled: false

ska-csp-lmc-mid:
  enabled: true
  ska-tango-base: 
    enabled: false

## sdp
ska-sdp:
  enabled: true
  lmc:
    prefix: mid
    nsubarray: 3
  ska-tango-base:
    enabled: false

## tm
ska-tmc-mid:
  enabled: true
  
## tm-simulator
ska-tmc-mid-simulators:
  deviceServers:
    cspmastersimulator:
      enabled: true
     
    sdpmastersimulator:
      enabled: false
     
    cspsubarraysimulator:
      enabled: false
    
    sdpsubarraysimulator:
      enabled: false
  

## SKUID
ska-ser-skuid:
  enabled: true
  skuid:
    use_pv: false
    config:
      generator_id: mvp01