display: ":0"
xauthority: "~/.Xauthority"

enabled: true

system: SW-infrastructure
subsystem: ska-tmc-sdpleafnodes
telescope: SKA-mid

subarray_count: 1
dishes: ["01"]

labels:
  app: ska-tmc-sdpleafnodes

global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000
  retry:
    - "--tries=10"
    - "--sleep=5"

dsconfig:
  configuration_file: data/configuration.json
  timeout: 300s
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.12
    pullPolicy: IfNotPresent

itango:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-itango
    tag: 9.4.3
    pullPolicy: IfNotPresent

sdpleafnodes:
  image:
    registry: artefact.skao.int
    image: ska-tmc-sdpleafnodes
    tag: 0.16.0
    pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 150m
    memory: 150Mi
  requests:
    cpu: 50m
    memory: 50Mi

deviceServers:
  mocks:
    enabled: true
    component:
      sdp: true
    mid:
      file: "data/mockdevicesmid.yaml"
    low:
      file: "data/mockdeviceslow.yaml"
    instances: ["01"]
  sdpsln:
    enabled: true
    instances: ["01"]
    subarray_count: 1
    mid:
      file: "data/sdpsubarrayleafnodemid.yaml"
      SdpSubarrayFQDN: "mid-sdp/subarray/01"
    low:
      file: "data/sdpsubarrayleafnodelow.yaml"
      SdpSubarrayFQDN: "low-sdp/subarray/01"
  sdpmln:
    enabled: true
    instances: ["01"]
    subarray_count: 1
    mid:
      file: "data/sdpmasterleafnodemid.yaml"
      SdpMasterFQDN: "mid-sdp/control/0"
    low:
      file: "data/sdpmasterleafnodelow.yaml"
      SdpMasterFQDN: "low-sdp/control/0"

nodeSelector: {}

affinity: {}

tolerations: []
