display: ":0"
xauthority: "~/.Xauthority"

enabled: true

system: SW-infrastructure
subsystem: ska-tmc-sdpleafnodes
telescope: SKA-mid

subarray_count: 1
dishes: ["01"]

labels:
  app: ska-tmc-sdpleafnodes

global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000
  retry:
  - "--tries=10"
  - "--sleep=5"

dsconfig:
  configuration_file: data/configuration.json
  timeout: 300s
  image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-dsconfig
      tag: 1.5.1
      pullPolicy: IfNotPresent

itango:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-itango
    tag: 9.3.5
    pullPolicy: IfNotPresent


sdpleafnodes:
  image:
    registry: artefact.skao.int
    image: ska-tmc-sdpleafnodes
    tag: 0.8.16
    pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 150m
    memory: 150Mi
  requests:
    cpu: 50m
    memory: 50Mi

deviceServers:
  mocks:
    enabled: true
    component:
      sdp: true
      csp: true
      dish: true
    instances: ["01"]
    file: "data/mockdevices.yaml"
  sdpsln:
    enabled: true
    instances: ["01"]
    subarray_count: 1
    file: "data/sdpsubarrayleafnode.yaml"
    SdpSubarrayFQDN: "mid_sdp/elt/subarray_1"
  sdpmln:
    enabled: true
    instances: ["01"]
    subarray_count: 1
    file: "data/sdpmasterleafnode.yaml"
    SdpMasterFQDN: "mid_sdp/elt/master"

nodeSelector: {}

affinity: {}

tolerations: []
