# GitLab CI in conjunction with GitLab Runner can use Docker Engine to test and build any application.
# Docker, when used with GitLab CI, runs each job in a separate and isolated container using the predefined image that is set up in .gitlab-ci.yml.
# In this case we use the latest python docker image to build and test this project.
image: $SKA_K8S_TOOLS_DOCKER_BUILDER_IMAGE

variables:
  GIT_SUBMODULE_STRATEGY: recursive

# cache is used to specify a list of files and directories which should be cached between jobs. You can only use paths that are within the project workspace.
# If cache is defined outside the scope of jobs, it means it is set globally and all jobs will use that definition
cache:
  paths:
    - build

# The YAML file defines a set of jobs with constraints stating when they should be run.
# You can specify an unlimited number of jobs which are defined as top-level elements with an arbitrary name and always have to contain at least the script clause.
# In this case we have only the test job which produce an artifacts (it must be placed into a directory called "public")
# It is also specified that only the master branch will be subject of this job.

stages:
  - lint
  - join-reports
  - build
  - test
  - publish
  - pages
  - scan
  - lifecycle

join_linting_reports:
  stage: join-reports
  tags:
    - k8srunner
  script:
    - echo "This step is needed as the artifacts can't be passed in the same stage"
    - make join-lint-reports
  artifacts:
    paths:
      - build/
    when: always

include:
# # # Helm Chart linting and Publish
# Note: Commenting this part to Disable helm chart linting and Publish job from the pipeline 
# - project: 'ska-telescope/templates-repository'
#   file: 'gitlab-ci/includes/helm-chart.gitlab-ci.yml'

# # Python packages build,lint, test and publish
- project: 'ska-telescope/templates-repository'
  file: 'gitlab-ci/includes/python.gitlab-ci.yml'

# # OCI images build and publish
- project: 'ska-telescope/templates-repository'
  file: 'gitlab-ci/includes/oci-image.gitlab-ci.yml'

# # Docs pages
- project: 'ska-telescope/templates-repository'
  file: 'gitlab-ci/includes/docs.gitlab-ci.yml'

# k8s steps
- project: 'ska-telescope/templates-repository'
  file: 'gitlab-ci/includes/k8s.gitlab-ci.yml'

# Create Gitlab CI badges from CI metrics
# https://developer.skatelescope.org/en/latest/tools/continuousintegration.html#automated-collection-of-ci-health-metrics-as-part-of-the-ci-pipeline
- project: 'ska-telescope/templates-repository'
  file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'

# Release Automation
- project: 'ska-telescope/templates-repository'
  file: 'gitlab-ci/includes/release.gitlab-ci.yml'


# k8s test stage template

k8s-low-test:
  extends: 
    - k8s-test
  variables:
    TELESCOPE: 'SKA-low'
    CONFIG: 'low'
    KUBE_NAMESPACE: 'ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-$CONFIG'
  environment:
    name: test/$CI_COMMIT_REF_SLUG-$CONFIG
    on_stop: stop-k8s-test-low
    auto_stop_in: 1 minute

stop-k8s-test-low:
  extends:
    - stop-k8s-test
  variables:
    TELESCOPE: 'SKA-low'
    CONFIG: 'low'
    KUBE_NAMESPACE: 'ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-$CONFIG'
  environment:
    name: test/$CI_COMMIT_REF_SLUG-$CONFIG
    action: stop

docs-build-rtd:
  rules:
    - when: never

