#
# Docker compose file for TANGO database and database device server
#
# Defines:
#   - tangodb: MariaDB database with TANGO schema
#   - databaseds: TANGO database device server
#
# Requires:
#   - None
#
version: '2'
volumes:
  tangodb: {}

services:
  tangodb:
    image: ska-registry.av.it.pt/ska-docker/tango-db:latest
    depends_on:
      - rsyslog-tmcprototype
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=tango
      - MYSQL_USER=tango
      - MYSQL_PASSWORD=tango
    volumes:
      - tangodb:/var/lib/mysql

  databaseds:
    image: ska-registry.av.it.pt/ska-docker/tango-cpp:latest
    depends_on:
      - tangodb
    environment:
      - MYSQL_HOST=tangodb:3306
      - MYSQL_DATABASE=tango
      - MYSQL_USER=tango
      - MYSQL_PASSWORD=tango
      - TANGO_HOST=databaseds:10000
    entrypoint:
      - /usr/local/bin/wait-for-it.sh
      - tangodb:3306
      - --timeout=30
      - --strict
      - --
      - /usr/local/bin/DataBaseds
      - "2"
      - -ORBendPoint
      - giop:tcp::10000

  tmcprototype:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - rsyslog-tmcprototype
    environment:
      - TANGO_HOST=databaseds:10000
    command: >
      sh -c "wait-for-it.sh databaseds:10000 --timeout=30 --strict --
             tango_admin --add-server DishMaster/test DishMaster test/DishMaster/01 &&\
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             /venv/bin/python /app/tmcprototype/DishMaster/DishMaster/DishMaster.py test"
    volumes_from:
      - rsyslog-tmcprototype:rw

  dishleafnode:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - rsyslog-tmcprototype
      - tmcprototype
    environment:
      - TANGO_HOST=databaseds:10000
    command: >
      sh -c "wait-for-it.sh databaseds:10000 --timeout=30 --strict --
             tango_admin --add-server DishLeafNode/test DishLeafNode test/DishLeafNode/01 &&\
             tango_admin --add-property test/DishLeafNode/01 DishMasterFQDN test/DishMaster/01 &&\
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             tango_admin --check-device test/DishMaster/01 &&\
             tango_admin --ping-device test/DishMaster/01 10 &&\
             /venv/bin/python /app/tmcprototype/DishLeafNode/DishLeafNode/DishLeafNode.py test"
    volumes_from:
      - rsyslog-tmcprototype:rw

  rsyslog-tmcprototype:
    container_name: rsyslog-tmcprototype
    image: jumanjiman/rsyslog
