apiVersion: v2
name: test-parent
description: An umbrella Helm chart for ska-tmc-sdpleafnodes deployment.
type: application
version: 0.0.6
appVersion: 0.3.6
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
maintainers:
  - name: Aditya Dange
    email: adityadange.ska@gmail.com
  - name: Kalyani Thigale
    email: kalyanit.ska@gmail.com
  - name: Shraddha Bajare
    email: shraddhab.ska@gmail.com
dependencies:
  - name: ska-tango-base
    version: 0.4.13
    repository: https://artefact.skao.int/repository/helm-internal
  - name: ska-tango-util
    version: 0.4.13
    repository: https://artefact.skao.int/repository/helm-internal
  - name: ska-tmc-sdpleafnodes
    version: 0.19.0
    repository: file://../ska-tmc-sdpleafnodes
    alias: tmc-sdpleafnodes
  - name: ska-taranta
    version: 1.0.29
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-taranta.enabled
