---

###########################################
##     PRINT STUFF
###########################################

- name: Print software_root directory
  debug: msg="rootdir = {{software_root}}"


###########################################
##     Pip install working directories
###########################################

- block:
  - name: Generate skabase
    command: pogo -src {{item}}.xmi
    args:
        chdir: "{{software_root}}/lmc-base-classes/skabase/{{item}}"
    environment:
        DISPLAY: "localhost:1.0"
    with_items:
      - SKABaseDevice
      - SKAObsDevice
      - SKAMaster
      - SKASubarray
      - SKACapability
      - SKAAlarmHandler
      - SKATelState
      - SKALogger
  tags:
    - generate-sw-skabase

- block:
  - name: Generate refelt
    command: pogo -src {{item}}.xmi
    args:
        chdir: "{{software_root}}/lmc-base-classes/refelt/refelt"
    environment:
        DISPLAY: "localhost:1.0"
    with_items:
      - RefMaster
      - RefA
      - Pdu
      - Rack
      - RefAchild
      - RefAlarmHandler
      - RefB
      - RefBchild
      - RefCapabilityA
      - RefSubarray
      - RefTelState
      - Server
      - Switch
  tags:
    - generate-sw-refelt

- block:
  - name: Generate refelt simlib
    become: yes
    command: >
        tango-simlib-generator
        --sim-data-file {{software_root}}/lmc-base-classes/refelt/refelt/{{item}}.xmi
        --dserver-name SvrSim{{item}}
        --directory /usr/local/bin/
    with_items:
      - Pdu
      - Rack
      - Server
      - Switch
  tags:
    - generate-sw-refelt-simlib

...
