---

###########################################
##     PRINT STUFF
###########################################

- name: Print software_root directory
  debug: msg="rootdir = {{software_root}}"

###########################################
##     Clone repos
###########################################

## lmc-base-classes

- name: Check for lmc-base-classes in software_root
  stat: path={{software_root}}/lmc-base-classes
  register: p_lmc_base_classes
  tags:
    - deploy-sw-lmc-base-classes

- name: Clone lmc-base-classes if dir not existing
  command: git clone https://github.com/ska-telescope/lmc-base-classes {{software_root}}/lmc-base-classes
  when: not p_lmc_base_classes.stat.exists
  tags:
    - deploy-sw-lmc-base-classes

- name: Git pull lmc-base-classes if dir exists
  command: git -C {{software_root}}/lmc-base-classes pull
  when: p_lmc_base_classes.stat.isdir is defined and p_lmc_base_classes.stat.isdir
  tags:
    - deploy-sw-lmc-base-classes

...
