display: ":0"
xauthority: "~/.Xauthority"
minikube: true

system: TM-low
telescope: SKA-low

global:
  labels:
    app: tmc-prototype
  annotations:
    app.gitlab.com/app: CI_PROJECT_PATH_SLUG
    app.gitlab.com/env: CI_ENVIRONMENT_SLUG
  tango_host: databaseds-tango-base-test:10000
  environment_variables: []
  dsconfig:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-dsconfig
      tag: 1.5.0
      pullPolicy: IfNotPresent
  itango:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-itango
      tag: 9.3.1
      pullPolicy: IfNotPresent

mccs: 
  tango-base:
    enabled: false

tmc-proto: 
  dsconfig:
    configuration_file: data/tmc-low-config.json

  ## this list has to change 
  deviceServers:
    - name: subarraynode1
      subsystem: subarray1
      function: observation-execution
      domain: subarray
      image: "{{ .Values.tmcprototype.image.registry }}/{{ .Values.tmcprototype.image.image }}:{{ .Values.tmcprototype.image.tag }}"
      imagePullPolicy: "{{ .Values.tmcprototype.image.pullPolicy }}"
      command:
        - sh
      args:
        - -c
        - "retry --max=10 -- tango_admin --ping-device ska_low/tm_leaf_node/mccs_subarray01 &&\
              /usr/local/bin/SubarrayNodeLowDS sa1"

    - name: centralnode
      subsystem: monitoring
      function: telescope-monitoring
      domain: general-monitoring
      image: "{{ .Values.tmcprototype.image.registry }}/{{ .Values.tmcprototype.image.image }}:{{ .Values.tmcprototype.image.tag }}"
      imagePullPolicy: "{{ .Values.tmcprototype.image.pullPolicy }}"
      command:
        - sh
      args:
        - -c
        - "retry --max=10 -- tango_admin --ping-device ska_low/tm_subarray_node/1 &&\
              /usr/local/bin/CentralNodeLowDS 01"

    - name: tm-alarmhandler
      subsystem: alarm-management
      function: alarm-management
      domain: general-monitoring
      image: "{{ .Values.tmalarmhandler.image.registry }}/{{ .Values.tmalarmhandler.image.image }}:{{ .Values.tmalarmhandler.image.tag }}"
      imagePullPolicy: "{{ .Values.tmalarmhandler.image.pullPolicy }}"
      command:
        - sh
      args:
        - -c
        - "./app/alarmhandler-srv 01"

tango-base:
  vnc:
    enabled: true
  tangorest:
    enabled: true
  tangotest:
    enabled: true
  ingress:
    enabled: true
  tangodb:
    use_pv: false

logging:
  elastic:
    enabled: false
  fluentd:
    enabled: false
  kibana:
    enabled: false
  tests:
    enabled: false

webjive:
  ingress:
    enabled: true
    nginx: false
    hostname: integration.engageska-portugal.pt
