
display: ":0"
xauthority: "~/.Xauthority"
minikube: true

system: TM-low
telescope: SKA-low

tango-base:
  vnc:
    enabled: false
  tangorest:
    enabled: false
  tangotest:
    enabled: false
  ingress:
    enabled: false
  tangodb:
    use_pv: false

logging:
  elastic:
    enabled: false
  fluentd:
    enabled: false
  kibana:
    enabled: false
  tests:
    enabled: false

webjive:
  ingress:
    enabled: true
    nginx: false
    hostname: integration.engageska-portugal.pt

mccs:
  mccs:
    enabled: true
  cli:
    enabled: true

  project:
    name: mccs
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: ska-low-mccs
      tag: latest
      pullPolicy: IfNotPresent
    
