display: ":0"
xauthority: "~/.Xauthority"

global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000
  sub-system:
    tango-base:
      enabled: false

mccs: 
  tango-base:
    enabled: false

# Set minikube=true when deploying on minikube
webjive:
  minikube: true

