display: ":0"
xauthority: "~/.Xauthority"
minikube: true

system: TM-low
telescope: SKA-low

global:
  system: TM-mid
  telescope: SKA-mid
  dsconfig_file: data/tmc-low-config.json

tmc-proto: 
  display: ":0"
  xauthority: "~/.Xauthority"

  system: TM-low
  telescope: SKA-low

  tmcprototype:
    enabled: true
    image:
      registry: nexus.engageska-portugal.pt/tango-example
      image: tmcprototype
      tag: 0.2.11
      pullPolicy: IfNotPresent

  tmalarmhandler:
    enabled: true
    image:
      registry: nexus.engageska-portugal.pt/tango-example
      image: tmalarmhandler
      tag: latest
      pullPolicy: Always

  dsconfig:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-dsconfig
      tag: 1.2.5.1
      pullPolicy: IfNotPresent

  deviceServers:
    - name: subarraynode1
      subsystem: subarray1
      function: observation-execution
      domain: subarray
      image: "{{ .Values.tmcprototype.image.registry }}/{{ .Values.tmcprototype.image.image }}:{{ .Values.tmcprototype.image.tag }}"
      imagePullPolicy: "{{ .Values.tmcprototype.image.pullPolicy }}"
      command:
        - sh
      args:
        - -c
        - "retry --max=10 -- tango_admin --ping-device ska_low/tm_leaf_node/mccs_subarray01 &&\
              /usr/local/bin/SubarrayNodeLowDS sa1"

    - name: centralnode
      subsystem: monitoring
      function: telescope-monitoring
      domain: general-monitoring
      image: "{{ .Values.tmcprototype.image.registry }}/{{ .Values.tmcprototype.image.image }}:{{ .Values.tmcprototype.image.tag }}"
      imagePullPolicy: "{{ .Values.tmcprototype.image.pullPolicy }}"
      command:
        - sh
      args:
        - -c
        - "retry --max=10 -- tango_admin --ping-device ska_low/tm_subarray_node/1 &&\
              /usr/local/bin/CentralNodeLowDS 01"

    - name: tm-alarmhandler
      subsystem: alarm-management
      function: alarm-management
      domain: general-monitoring
      image: "{{ .Values.tmalarmhandler.image.registry }}/{{ .Values.tmalarmhandler.image.image }}:{{ .Values.tmalarmhandler.image.tag }}"
      imagePullPolicy: "{{ .Values.tmalarmhandler.image.pullPolicy }}"
      command:
        - sh
      args:
        - -c
        - "./app/alarmhandler-srv 01"

tango-base:
  vnc:
    enabled: true
  tangorest:
    enabled: true
  tangotest:
    enabled: true
  ingress:
    enabled: true
  tangodb:
    use_pv: false

logging:
  elastic:
    enabled: false
  fluentd:
    enabled: false
  kibana:
    enabled: false
  tests:
    enabled: false

webjive:
  ingress:
    enabled: true
    nginx: false
    hostname: integration.engageska-portugal.pt
