version: '2'
volumes:
  tangodb: {}

services:
  cbfmaster:
    image: ${DOCKER_REGISTRY_HOST}/ska-docker/mid-cbf-mcs:0.4.0
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}cbfmaster
    depends_on:
      - databaseds
      - csp-dsconfig
      - vcc001
      - vcc002
      - vcc003
      - vcc004
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             retry --max=5 -- tango_admin --ping-device mid_csp_cbf/vcc/001 &&\
             retry --max=5 -- tango_admin --ping-device mid_csp_cbf/vcc/002 &&\
             retry --max=5 -- tango_admin --ping-device mid_csp_cbf/vcc/003 &&\
             retry --max=5 -- tango_admin --ping-device mid_csp_cbf/vcc/004 &&\
             /venv/bin/python /app/tangods/CbfMaster/CbfMaster/CbfMaster.py master"

  cbfsubarray01:
    image: ${DOCKER_REGISTRY_HOST}/ska-docker/mid-cbf-mcs:0.4.0
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}cbfsubarray01
    depends_on:
      - csp-dsconfig
      - vcc001
      - vcc002
      - vcc003
      - vcc004
      - cbfmaster
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             retry --max=5 -- tango_admin --ping-device mid_csp_cbf/sub_elt/master &&\
             /venv/bin/python /app/tangods/CbfSubarray/CbfSubarrayMulti/CbfSubarrayMulti.py cbfSubarray-01"

  cbfsubarray02:
    image: ${DOCKER_REGISTRY_HOST}/ska-docker/mid-cbf-mcs:0.4.0
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}cbfsubarray02
    depends_on:
      - csp-dsconfig
      - vcc001
      - vcc002
      - vcc003
      - vcc004
      - cbfmaster
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             retry --max=5 -- tango_admin --ping-device mid_csp_cbf/sub_elt/master &&\
             /venv/bin/python /app/tangods/CbfSubarray/CbfSubarrayMulti/CbfSubarrayMulti.py cbfSubarray-02"

  cbfsubarray03:
    image: ${DOCKER_REGISTRY_HOST}/ska-docker/mid-cbf-mcs:0.4.0
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}cbfsubarray03
    depends_on:
      - csp-dsconfig
      - vcc001
      - vcc002
      - vcc003
      - vcc004
      - cbfmaster
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             retry --max=5 -- tango_admin --ping-device mid_csp_cbf/sub_elt/master &&\
             /venv/bin/python /app/tangods/CbfSubarray/CbfSubarrayMulti/CbfSubarrayMulti.py cbfSubarray-03"

  vcc001:
    image: ${DOCKER_REGISTRY_HOST}/ska-docker/mid-cbf-mcs:0.4.0
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}vcc001
    depends_on:
      - databaseds
      - csp-dsconfig
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             /venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-001"

  vcc002:
    image: ${DOCKER_REGISTRY_HOST}/ska-docker/mid-cbf-mcs:0.4.0
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}vcc002
    depends_on:
      - databaseds
      - csp-dsconfig
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             /venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-002"

  vcc003:
    image: ${DOCKER_REGISTRY_HOST}/ska-docker/mid-cbf-mcs:0.4.0
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}vcc003
    depends_on:
      - databaseds
      - csp-dsconfig
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             /venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-003"

  vcc004:
    image: ${DOCKER_REGISTRY_HOST}/ska-docker/mid-cbf-mcs:0.4.0
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}vcc004
    depends_on:
      - databaseds
      - csp-dsconfig
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             /venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-004"

  fsp01:
    image: ${DOCKER_REGISTRY_HOST}/ska-docker/mid-cbf-mcs:0.4.0
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}fsp01
    depends_on:
      - vcc001
      - vcc002
      - vcc003
      - vcc004
      - databaseds
      - csp-dsconfig
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
       sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
              /venv/bin/python /app/tangods/Fsp/FspMulti/FspMulti.py fsp-01"
#      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
#             tango_admin --check-device mid_csp_cbf/fsp_corr/01 &&\
#             tango_admin --check-device mid_csp_cbf/fsp_pss/01 &&\
#             tango_admin --check-device mid_csp_cbf/fsp_pst/01 &&\
#             tango_admin --check-device mid_csp_cbf/fsp_vlbi/01 &&\
#             for j in $$(seq -w 1 16); do \
#             tango_admin --check-device mid_csp_cbf/fspSubarray/01\_$$j; done &&\
#             tango_admin --check-device mid_csp_cbf/fsp/01 &&\
#             /venv/bin/python -u -v4 /app/csplmc/Fsp/FspMulti/FspMulti.py fsp-01"