#
# Docker compose file for setting up DSH LMC devices in CI environment.
# The current setup provides one container each for SDP Master and SDP Subarray device.
# Defines:
#   - dish-master: DishMaster device service
#   - ds-simulator: DSSimulator device service
#   - dsctrl-simulator: DSCtrlSimulator device service
#   - lmc-logger: LMCLogger device service
#   - rx-simulator: RxSimulator device service
#   - spf-simulator: SPFSimulator device service
# Requires:
#   - tango-docker-compose.yml

version: '2.2'
volumes:
  tangodb: {}

services:
  dish-master-1:
    image: ${DOCKER_REGISTRY_HOST}/ska-telescope/dsh_lmc_prototype:0.1.0
    depends_on:
      - databaseds
      - dshlmc-dsconfig
      - ds-simulator-1
      - dsctrl-simulator-1
      - lmc-logger-1
      - rx-simulator-1
      - spf-simulator-1
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dish-master-1
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "./bin/dish-master 1"
  
  dish-master-2:
    image: ${DOCKER_REGISTRY_HOST}/ska-telescope/dsh_lmc_prototype:0.1.0
    depends_on:
      - databaseds
      - dshlmc-dsconfig
      - ds-simulator-2
      - dsctrl-simulator-2
      - lmc-logger-2
      - rx-simulator-2
      - spf-simulator-2
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dish-master-2
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "./bin/dish-master 2"

  dish-master-3:
    image: ${DOCKER_REGISTRY_HOST}/ska-telescope/dsh_lmc_prototype:0.1.0
    depends_on:
      - databaseds
      - dshlmc-dsconfig
      - ds-simulator-3
      - dsctrl-simulator-3
      - lmc-logger-3
      - rx-simulator-3
      - spf-simulator-3
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dish-master-3
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "./bin/dish-master 3"

  dish-master-4:
    image: ${DOCKER_REGISTRY_HOST}/ska-telescope/dsh_lmc_prototype:0.1.0
    depends_on:
      - databaseds
      - dshlmc-dsconfig
      - ds-simulator-4
      - dsctrl-simulator-4
      - lmc-logger-4
      - rx-simulator-4
      - spf-simulator-4
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dish-master-4
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "./bin/dish-master 4"

  ds-simulator-1:
    image: ${DOCKER_REGISTRY_HOST}/ska-telescope/dsh_lmc_prototype:0.1.0
    depends_on:
      - databaseds
      - dshlmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}ds-simulator-1
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "./bin/ds-simulator 1"

  ds-simulator-2:
    image: ${DOCKER_REGISTRY_HOST}/ska-telescope/dsh_lmc_prototype:0.1.0
    depends_on:
      - databaseds
      - dshlmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}ds-simulator-2
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "./bin/ds-simulator 2"

  ds-simulator-3:
    image: ${DOCKER_REGISTRY_HOST}/ska-telescope/dsh_lmc_prototype:0.1.0
    depends_on:
      - databaseds
      - dshlmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}ds-simulator-3
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "./bin/ds-simulator 3"

  ds-simulator-4:
    image: ${DOCKER_REGISTRY_HOST}/ska-telescope/dsh_lmc_prototype:0.1.0
    depends_on:
      - databaseds
      - dshlmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}ds-simulator-4
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "./bin/ds-simulator 4"
             
  dsctrl-simulator-1:
    image: ${DOCKER_REGISTRY_HOST}/ska-telescope/dsh_lmc_prototype:0.1.0
    depends_on:
      - databaseds
      - dshlmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dsctrl-simulator-1
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "./bin/dsctrl-simulator 1"

  dsctrl-simulator-2:
    image: ${DOCKER_REGISTRY_HOST}/ska-telescope/dsh_lmc_prototype:0.1.0
    depends_on:
      - databaseds
      - dshlmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dsctrl-simulator-2
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "./bin/dsctrl-simulator 2"

  dsctrl-simulator-3:
    image: ${DOCKER_REGISTRY_HOST}/ska-telescope/dsh_lmc_prototype:0.1.0
    depends_on:
      - databaseds
      - dshlmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dsctrl-simulator-3
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "./bin/dsctrl-simulator 3"

  dsctrl-simulator-4:
    image: ${DOCKER_REGISTRY_HOST}/ska-telescope/dsh_lmc_prototype:0.1.0
    depends_on:
      - databaseds
      - dshlmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dsctrl-simulator-4
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "./bin/dsctrl-simulator 4"

  lmc-logger-1:
    image: ${DOCKER_REGISTRY_HOST}/ska-telescope/dsh_lmc_prototype:0.1.0
    depends_on:
      - databaseds
      - dshlmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}lmc-logger-1
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "./bin/lmc-logger 1"
  
  lmc-logger-2:
    image: ${DOCKER_REGISTRY_HOST}/ska-telescope/dsh_lmc_prototype:0.1.0
    depends_on:
      - databaseds
      - dshlmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}lmc-logger-2
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "./bin/lmc-logger 2"
          
  lmc-logger-3:
    image: ${DOCKER_REGISTRY_HOST}/ska-telescope/dsh_lmc_prototype:0.1.0
    depends_on:
      - databaseds
      - dshlmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}lmc-logger-3
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "./bin/lmc-logger 3"

  lmc-logger-4:
    image: ${DOCKER_REGISTRY_HOST}/ska-telescope/dsh_lmc_prototype:0.1.0
    depends_on:
      - databaseds
      - dshlmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}lmc-logger-4
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "./bin/lmc-logger 4"

  rx-simulator-1:
    image: ${DOCKER_REGISTRY_HOST}/ska-telescope/dsh_lmc_prototype:0.1.0
    depends_on:
      - databaseds
      - dshlmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}rx-simulator5
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "./bin/rx-simulator 1"

  rx-simulator-2:
    image: ${DOCKER_REGISTRY_HOST}/ska-telescope/dsh_lmc_prototype:0.1.0
    depends_on:
      - databaseds
      - dshlmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}rx-simulator6
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "./bin/rx-simulator 2"

  rx-simulator-3:
    image: ${DOCKER_REGISTRY_HOST}/ska-telescope/dsh_lmc_prototype:0.1.0
    depends_on:
      - databaseds
      - dshlmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}rx-simulator7
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "./bin/rx-simulator 3"

  rx-simulator-4:
    image: ${DOCKER_REGISTRY_HOST}/ska-telescope/dsh_lmc_prototype:0.1.0
    depends_on:
      - databaseds
      - dshlmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}rx-simulator8
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "./bin/rx-simulator 4"      

  spf-simulator-1:
    image: ${DOCKER_REGISTRY_HOST}/ska-telescope/dsh_lmc_prototype:0.1.0
    depends_on:
      - databaseds
      - dshlmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}spf-simulator5
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "./bin/spf-simulator 1"

  spf-simulator-2:
    image: ${DOCKER_REGISTRY_HOST}/ska-telescope/dsh_lmc_prototype:0.1.0
    depends_on:
      - databaseds
      - dshlmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}spf-simulator6
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "./bin/spf-simulator 2"

  spf-simulator-3:
    image: ${DOCKER_REGISTRY_HOST}/ska-telescope/dsh_lmc_prototype:0.1.0
    depends_on:
      - databaseds
      - dshlmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}spf-simulator7
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "./bin/spf-simulator 3"

  spf-simulator-4:
    image: ${DOCKER_REGISTRY_HOST}/ska-telescope/dsh_lmc_prototype:0.1.0
    depends_on:
      - databaseds
      - dshlmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}spf-simulator8
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "./bin/spf-simulator 4"

  dshlmc-dsconfig:
    image: ${DOCKER_REGISTRY_HOST}/ska-docker/tango-dsconfig:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dshlmc-dsconfig
    depends_on:
      - databaseds
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             json2tango -w -a -u /tmc-prototype/data/dshlmc_config.json &&
             sleep infinity"
    volumes:
      - ..:/tmc-prototype