#
# Docker compose file for testing the TMC prototype in CI environment.
# The current setup provides one container each for Central Node, two Subarray Nodes
# in two separate containers, CspMasterLeafNode, SdpMasterLeafNode,
# four Dish Leaf Nodes in four separate containers, four Dish Masters in
# four separate containers, tmclogger, rsyslog service (for logging) and tmalarmhandler.
# Defines:
#   - rsyslog-tmcprototype: rsyslog service for logger
#   - dishmaster: Simulator of Dish Master device
#   - dishleafnode: Dish Leaf Node
#   - sdpsubarrayleafnode: SDP Subarray Leaf Node
#   - subarraynode: Subarray Node
#   - centralnode: Central Node
#   - cspmasterleafnode: CSP Master Leaf Node
#   - tmclogger: Logger for TMC
#   - tm-alarmhandler: TM AlarmHandler service
#   - configure-alarms: Alarm configuration for TM AlarmHandler
# Requires:
#   - tango-docker-compose.yml
#
# TODO: Some of the containers and part is commented out for future use
version: '2'
volumes:
  tangodb: {}

services:
  tangodb:
    image: nexus.engageska-portugal.pt/ska-docker/tango-db:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}tangodb
    depends_on:
      - rsyslog-tmcprototype
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=tango
      - MYSQL_USER=tango
      - MYSQL_PASSWORD=tango
    volumes:
      - tangodb:/var/lib/mysql

  databaseds:
    image: nexus.engageska-portugal.pt/ska-docker/tango-cpp:latest
    depends_on:
      - tangodb
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}databaseds
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=tango
      - MYSQL_USER=tango
      - MYSQL_PASSWORD=tango
      - TANGO_HOST=${TANGO_HOST}
    entrypoint:
      - /usr/local/bin/wait-for-it.sh
      - ${MYSQL_HOST}
      - --timeout=30
      - --strict
      - --
      - /usr/local/bin/DataBaseds
      - "2"
      - -ORBendPoint
      - giop:tcp::10000

  tmclogger:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/lmcbaseclasses:latest
    depends_on:
    - databaseds
    - rsyslog-tmcprototype
    - tmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}logger
    environment:
    - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             /venv/bin/python -u /app/skabase/SKALogger/SKALogger.py Ref"
    volumes_from:
        - rsyslog-tmcprototype:rw

  dishmaster1:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - rsyslog-tmcprototype
      - tmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishmaster1
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             /venv/bin/python /app/tmcprototype/DishMaster/DishMaster/DishMaster.py 01"
    volumes_from:
      - rsyslog-tmcprototype:rw

  dishmaster2:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - rsyslog-tmcprototype
      - tmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishmaster2
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             /venv/bin/python /app/tmcprototype/DishMaster/DishMaster/DishMaster.py 02"
    volumes_from:
      - rsyslog-tmcprototype:rw

  dishmaster3:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - rsyslog-tmcprototype
      - tmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishmaster3
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             /venv/bin/python /app/tmcprototype/DishMaster/DishMaster/DishMaster.py 03"
    volumes_from:
      - rsyslog-tmcprototype:rw

  dishmaster4:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - rsyslog-tmcprototype
      - tmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishmaster4
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             /venv/bin/python /app/tmcprototype/DishMaster/DishMaster/DishMaster.py 04"
    volumes_from:
      - rsyslog-tmcprototype:rw

  dishleafnode1:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - rsyslog-tmcprototype
      - dishmaster1
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishleafnode1
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             tango_admin --ping-device mid_d0001/elt/master 10 &&\
             /venv/bin/python /app/tmcprototype/DishLeafNode/DishLeafNode/DishLeafNode.py 01"
    volumes_from:
      - rsyslog-tmcprototype:rw

  dishleafnode2:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - rsyslog-tmcprototype
      - dishmaster2
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishleafnode2
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             tango_admin --ping-device mid_d0002/elt/master 10 &&\
             /venv/bin/python /app/tmcprototype/DishLeafNode/DishLeafNode/DishLeafNode.py 02"
    volumes_from:
      - rsyslog-tmcprototype:rw

  dishleafnode3:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - rsyslog-tmcprototype
      - dishmaster3
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishleafnode3
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             tango_admin --ping-device mid_d0003/elt/master 10 &&\
             /venv/bin/python /app/tmcprototype/DishLeafNode/DishLeafNode/DishLeafNode.py 03"
    volumes_from:
      - rsyslog-tmcprototype:rw

  dishleafnode4:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - rsyslog-tmcprototype
      - dishmaster4
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishleafnode4
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             tango_admin --ping-device mid_d0004/elt/master 10 &&\
             /venv/bin/python /app/tmcprototype/DishLeafNode/DishLeafNode/DishLeafNode.py 04"
    volumes_from:
      - rsyslog-tmcprototype:rw

  cspsubarrayleafnode:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - rsyslog-tmcprototype
      - cspsubarray
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}cspsubarrayleafnode
    environment:
    - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             tango_admin --ping-device mid-csp/elt/subarray01 10 &&\
             /venv/bin/python /app/tmcprototype/CspSubarrayLeafNode/CspSubarrayLeafNode/CspSubarrayLeafNode.py 01"
    volumes_from:
    - rsyslog-tmcprototype:rw

  cspmasterleafnode:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
    - databaseds
    - rsyslog-tmcprototype
    - cspmaster
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}cspmasterleafnode
    environment:
    - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             tango_admin --ping-device mid_csp/elt/master 10 &&\
             /venv/bin/python /app/tmcprototype/CspMasterLeafNode/CspMasterLeafNode/CspMasterLeafNode.py 01"
    volumes_from:
    - rsyslog-tmcprototype:rw

  sdpsubarrayleafnode:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
    - databaseds
    - rsyslog-tmcprototype
    - sdpsubarray
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}sdpsubarrayleafnode
    environment:
    - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             tango_admin --ping-device mid_sdp/elt/subarray_00 10 &&\
             /venv/bin/python -u /app/tmcprototype/SdpSubarrayLeafNode/SdpSubarrayLeafNode/SdpSubarrayLeafNode.py 01"
    volumes_from:
    - rsyslog-tmcprototype:rw

  sdpmasterleafnode:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
    - databaseds
    - rsyslog-tmcprototype
    - sdpmaster
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}sdpmasterleafnode
    environment:
    - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             tango_admin --ping-device mid_sdp/elt/master 10 &&\
             /venv/bin/python /app/tmcprototype/SdpMasterLeafNode/SdpMasterLeafNode/SdpMasterLeafNode.py 01"
    volumes_from:
    - rsyslog-tmcprototype:rw

  subarraynode1:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - rsyslog-tmcprototype
      - dishleafnode1
      - dishleafnode2
      - dishleafnode3
      - dishleafnode4
      - sdpsubarrayleafnode
      - cspsubarrayleafnode
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}subarraynode1
    environment:
    - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             tango_admin --ping-device mid_d0001/elt/master 10 &&\
             tango_admin --ping-device mid_d0002/elt/master 10 &&\
             tango_admin --ping-device mid_d0003/elt/master 10 &&\
             tango_admin --ping-device mid_d0004/elt/master 10 &&\
             tango_admin --ping-device mid-csp/elt/subarray01 10 &&\
             tango_admin --ping-device mid_sdp/elt/subarray_00 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0001 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0002 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0003 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0004 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/csp_subarray 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/sdp_subarray 10 &&\
             /venv/bin/python /app/tmcprototype/SubarrayNode/SubarrayNode/SubarrayNode.py sa1"
    volumes_from:
    - rsyslog-tmcprototype:rw

  subarraynode2:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - rsyslog-tmcprototype
      - dishleafnode1
      - dishleafnode2
      - dishleafnode3
      - dishleafnode4
      - sdpsubarrayleafnode
      - cspsubarrayleafnode
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}subarraynode2
    environment:
    - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             tango_admin --ping-device mid_d0001/elt/master 10 &&\
             tango_admin --ping-device mid_d0002/elt/master 10 &&\
             tango_admin --ping-device mid_d0003/elt/master 10 &&\
             tango_admin --ping-device mid_d0004/elt/master 10 &&\
             tango_admin --ping-device mid-csp/elt/subarray01 10 &&\
             tango_admin --ping-device mid_sdp/elt/subarray_00 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0001 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0002 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0003 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0004 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/csp_subarray 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/sdp_subarray 10 &&\
             /venv/bin/python /app/tmcprototype/SubarrayNode/SubarrayNode/SubarrayNode.py sa2"
    volumes_from:
    - rsyslog-tmcprototype:rw

  centralnode:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - rsyslog-tmcprototype
      - subarraynode1
      - subarraynode2
      - cspmasterleafnode
      - sdpmasterleafnode
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}centralnode
    environment:
    - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             tango_admin --ping-device mid_d0001/elt/master 10 &&\
             tango_admin --ping-device mid_d0002/elt/master 10 &&\
             tango_admin --ping-device mid_d0003/elt/master 10 &&\
             tango_admin --ping-device mid_d0004/elt/master 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0001 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0002 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0003 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0004 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/sdp_master 10 &&\
             tango_admin --ping-device ska_mid/tm_subarray_node/1 10 &&\
             tango_admin --ping-device ska_mid/tm_subarray_node/2 10 &&\
             /venv/bin/python /app/tmcprototype/CentralNode/CentralNode/CentralNode.py 01"
    volumes_from:
    - rsyslog-tmcprototype:rw

  rsyslog-tmcprototype:
    image: jumanjiman/rsyslog
    container_name: ${CONTAINER_NAME_PREFIX}rsyslog
    network_mode: ${NETWORK_MODE}

# Required for future use
#  configurelogger:
#    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
#    depends_on:
#      - tmclogger
#      - dishmaster1
#      - dishmaster2
#      - dishmaster3
#      - dishmaster4
#      - sdpmaster
#      - cspsubarray
#      - sdpsubarray
#      - dishleafnode1
#      - dishleafnode2
#      - dishleafnode3
#      - dishleafnode4
#      - cspmasterleafnode
#      - sdpmasterleafnode
#      - subarraynode1
#      - subarraynode2
#      - sdpsubarrayleafnode
#      - cspsubarrayleafnode
#      - centralnode
#    network_mode: ${NETWORK_MODE}
#    container_name: ${CONTAINER_NAME_PREFIX}configurelogger
#    environment:
#    - TANGO_HOST=${TANGO_HOST}
#    command: >
#      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
#            /venv/bin/python /app/tmcprototype/configure_logging.py"

  tm-alarmhandler:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmalarmhandler
    depends_on:
      - databaseds
      - tmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}tmalarmhandler
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
            ./app/alarmhandler-srv 01"

  sdpmaster:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
    - databaseds
    - rsyslog-tmcprototype
    - tmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}sdpmaster
    environment:
    - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             /venv/bin/python /app/tmcprototype/SdpMaster/SdpMaster/SdpMaster.py 01"
    volumes_from:
    - rsyslog-tmcprototype:rw

# For future use
#  dsconfigdump:
#    image: nexus.engageska-portugal.pt/ska-docker/tango-dsconfig:latest
#    network_mode: ${NETWORK_MODE}
#    container_name: ${CONTAINER_NAME_PREFIX}dsconfigdump
#    depends_on:
#      - databaseds
#    environment:
#      - TANGO_HOST=${TANGO_HOST}
#    command: >
#      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
#             python -m dsconfig.dump && sleep infinity"

  tmc-dsconfig:
    image: ${DOCKER_REGISTRY_HOST}/ska-docker/tango-dsconfig:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}tmc-dsconfig
    depends_on:
      - databaseds
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             json2tango -w -a -u /tmc-prototype/data/tmc-devices.json &&
             sleep infinity"
    volumes:
      - ..:/tmc-prototype