#
# Docker compose file for testing the TMC prototype in CI environment.
# The current setup provides one container each for Central Node, two Subarray Nodes
# in two separate containers, CspMasterLeafNode, SdpMasterLeafNode,
# four Dish Leaf Nodes in four separate containers, four Dish Masters in
# four separate containers, tmclogger, rsyslog service (for logging) and tmalarmhandler.
# Defines:
#   - rsyslog-tmcprototype: rsyslog service for logger
#   - dishmaster: Simulator of Dish Master device
#   - dishleafnode: Dish Leaf Node
#   - sdpsubarrayleafnode: SDP Subarray Leaf Node
#   - subarraynode: Subarray Node
#   - centralnode: Central Node
#   - cspmasterleafnode: CSP Master Leaf Node
#   - tmclogger: Logger for TMC
#   - tm-alarmhandler: TM AlarmHandler service
#   - configure-alarms: Alarm configuration for TM AlarmHandler
# Requires:
#   - tango-docker-compose.yml
#
# TODO: Some of the containers and part is commented out for future use
version: '2'
volumes:
  tangodb: {}

services:
  tmclogger:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/lmcbaseclasses:latest
    depends_on:
      - databaseds
      - tmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}logger
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             /venv/bin/python -u /app/skabase/SKALogger/SKALogger.py Ref"

  dishmaster1:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - tmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishmaster1
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             /venv/bin/python -u /app/tmcprototype/DishMaster/DishMaster/DishMaster.py 01 v5"

  dishmaster2:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - tmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishmaster2
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             /venv/bin/python -u /app/tmcprototype/DishMaster/DishMaster/DishMaster.py 02 v5"

  dishmaster3:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - tmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishmaster3
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             /venv/bin/python -u /app/tmcprototype/DishMaster/DishMaster/DishMaster.py 03 v5"

  dishmaster4:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - tmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishmaster4
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             /venv/bin/python -u /app/tmcprototype/DishMaster/DishMaster/DishMaster.py 04 v5"

  dishleafnode1:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - dishmaster1
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishleafnode1
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             tango_admin --ping-device mid_d0001/elt/master 10 &&\
             /venv/bin/python -u /app/tmcprototype/DishLeafNode/DishLeafNode/DishLeafNode.py 01 v5"

  dishleafnode2:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - dishmaster2
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishleafnode2
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             tango_admin --ping-device mid_d0002/elt/master 10 &&\
             /venv/bin/python -u /app/tmcprototype/DishLeafNode/DishLeafNode/DishLeafNode.py 02 v5"

  dishleafnode3:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - dishmaster3
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishleafnode3
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             tango_admin --ping-device mid_d0003/elt/master 10 &&\
             /venv/bin/python -u /app/tmcprototype/DishLeafNode/DishLeafNode/DishLeafNode.py 03 v5"

  dishleafnode4:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - dishmaster4
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishleafnode4
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             tango_admin --ping-device mid_d0004/elt/master 10 &&\
             /venv/bin/python -u /app/tmcprototype/DishLeafNode/DishLeafNode/DishLeafNode.py 04 v5"

  cspsubarrayleafnode1:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - cspsubarray1
      - tmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}cspsubarrayleafnode1
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             tango_admin --ping-device mid_csp/elt/subarray_01 10 &&\
             /venv/bin/python -u /app/tmcprototype/CspSubarrayLeafNode/CspSubarrayLeafNode/CspSubarrayLeafNode.py 01 v5"

  cspsubarrayleafnode2:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - cspsubarray2
      - tmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}cspsubarrayleafnode2
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             tango_admin --ping-device mid_csp/elt/subarray_02 10 &&\
             /venv/bin/python -u /app/tmcprototype/CspSubarrayLeafNode/CspSubarrayLeafNode/CspSubarrayLeafNode.py 02 v5"

  cspsubarrayleafnode3:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - cspsubarray3
      - tmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}cspsubarrayleafnode3
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             tango_admin --ping-device mid_csp/elt/subarray_03 10 &&\
             /venv/bin/python -u /app/tmcprototype/CspSubarrayLeafNode/CspSubarrayLeafNode/CspSubarrayLeafNode.py 03 v5"

  cspmasterleafnode:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - cspmaster
      - tmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}cspmasterleafnode
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             tango_admin --ping-device mid_csp/elt/master 10 &&\
             /venv/bin/python -u /app/tmcprototype/CspMasterLeafNode/CspMasterLeafNode/CspMasterLeafNode.py 01 v5"

  sdpsubarrayleafnode1:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - sdpsubarray1
      - tmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}sdpsubarrayleafnode1
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             tango_admin --ping-device mid_sdp/elt/subarray_1 10 &&\
             /venv/bin/python -u /app/tmcprototype/SdpSubarrayLeafNode/SdpSubarrayLeafNode/SdpSubarrayLeafNode.py 01 v5"

  sdpsubarrayleafnode2:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - sdpsubarray2
      - tmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}sdpsubarrayleafnode2
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             tango_admin --ping-device mid_sdp/elt/subarray_2 10 &&\
             /venv/bin/python -u /app/tmcprototype/SdpSubarrayLeafNode/SdpSubarrayLeafNode/SdpSubarrayLeafNode.py 02 v5"

  sdpsubarrayleafnode3:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - sdpsubarray3
      - tmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}sdpsubarrayleafnode3
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             tango_admin --ping-device mid_sdp/elt/subarray_3 10 &&\
             /venv/bin/python -u /app/tmcprototype/SdpSubarrayLeafNode/SdpSubarrayLeafNode/SdpSubarrayLeafNode.py 03 v5"

  sdpmasterleafnode:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - sdpmaster
      - tmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}sdpmasterleafnode
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             tango_admin --ping-device mid_sdp/elt/master 10 &&\
             /venv/bin/python -u /app/tmcprototype/SdpMasterLeafNode/SdpMasterLeafNode/SdpMasterLeafNode.py 01 v5"

  subarraynode1:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - dishleafnode1
      - dishleafnode2
      - dishleafnode3
      - dishleafnode4
      - sdpsubarrayleafnode1
      - cspsubarrayleafnode1
      - tmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}subarraynode1
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             tango_admin --ping-device ska_mid/tm_leaf_node/d0001 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0002 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0003 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0004 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/csp_subarray01 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/sdp_subarray01 10 &&\
             /venv/bin/python -u /app/tmcprototype/SubarrayNode/SubarrayNode/SubarrayNode.py sa1 v5"

  subarraynode2:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - dishleafnode1
      - dishleafnode2
      - dishleafnode3
      - dishleafnode4
      - sdpsubarrayleafnode2
      - cspsubarrayleafnode2
      - tmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}subarraynode2
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             tango_admin --ping-device ska_mid/tm_leaf_node/d0001 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0002 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0003 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0004 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/csp_subarray02 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/sdp_subarray02 10 &&\
             /venv/bin/python -u /app/tmcprototype/SubarrayNode/SubarrayNode/SubarrayNode.py sa2 v5"

  subarraynode3:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - dishleafnode1
      - dishleafnode2
      - dishleafnode3
      - dishleafnode4
      - sdpsubarrayleafnode3
      - cspsubarrayleafnode3
      - tmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}subarraynode3
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             tango_admin --ping-device ska_mid/tm_leaf_node/d0001 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0002 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0003 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0004 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/csp_subarray03 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/sdp_subarray03 10 &&\
             /venv/bin/python -u /app/tmcprototype/SubarrayNode/SubarrayNode/SubarrayNode.py sa3 v5"

  centralnode:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmcprototype:latest
    depends_on:
      - databaseds
      - subarraynode1
      - subarraynode2
      - subarraynode3
      - cspmasterleafnode
      - sdpmasterleafnode
      - tmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}centralnode
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             tango_admin --ping-device ska_mid/tm_leaf_node/d0001 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0002 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0003 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0004 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/csp_master 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/sdp_master 10 &&\
             tango_admin --ping-device ska_mid/tm_subarray_node/1 10 &&\
             tango_admin --ping-device ska_mid/tm_subarray_node/2 10 &&\
             tango_admin --ping-device ska_mid/tm_subarray_node/3 10 &&\
             /venv/bin/python -u /app/tmcprototype/CentralNode/CentralNode/CentralNode.py 01 v5"

  tm-alarmhandler:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tmalarmhandler:latest
    depends_on:
      - databaseds
      - tmc-dsconfig
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}tmalarmhandler
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
            ./app/alarmhandler-srv 01 v5"

# For future use
#  dsconfigdump:
#    image: nexus.engageska-portugal.pt/ska-docker/tango-dsconfig:latest
#    network_mode: ${NETWORK_MODE}
#    container_name: ${CONTAINER_NAME_PREFIX}dsconfigdump
#    depends_on:
#      - databaseds
#    environment:
#      - TANGO_HOST=${TANGO_HOST}
#    command: >
#      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
#             python -m dsconfig.dump && sleep infinity"

  tmc-dsconfig:
    image: ${DOCKER_REGISTRY_HOST}/ska-docker/tango-dsconfig:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}tmc-dsconfig
    depends_on:
      - databaseds
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             json2tango -w -a -u /tmc-prototype/data/tmc-devices.json &&
             sleep infinity"
    volumes:
      - ..:/tmc-prototype