display: ":0"
xauthority: "~/.Xauthority"

global:
  retry: 
  - "--sleep=1"
  - "--tries=100"
  sub-system:
    ska-tango-base:
      enabled: false
    tango-base:
      enabled: false
    webjive:
      enabled: true
  minikube: false
  tango_host: databaseds-tango-base-test:10000
  dsconfig:
    timeout: 300s
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-dsconfig
      tag: 1.5.1
      pullPolicy: IfNotPresent

ska-tango-base:
  vnc:
    replicas: 1
    enabled: true
  tangorest:
    replicas: 1
    enabled: true
    resources:
      requests:
        cpu: 100m     # 100m = 0.1 CPU
        memory: 128Mi # 256Mi = 0.25 GB mem
        ephemeral-storage: 256Mi
      limits:
        cpu: 200m     # 100m = 0.1 CPU
        memory: 768Mi # 256Mi = 0.25 GB mem
        ephemeral-storage: 256Mi
  tangotest:
    enabled: true
  ingress:
    enabled: true
  tangodb:
    use_pv: false

tango-base:
    enabled: false

ska-low-mccs:
  ska-tango-base:
    enabled: false

webjive:
  minikube: false
  ingress:
    enabled: true
    nginx: true
    hostname: low.k8s.stfc.skao.int
  tangogql:
    replicas: 3
    resources:
      requests:
        cpu: 600m     # 600m = 0.6 CPU
        memory: 512Mi # 512Mi = 0.5 GB mem
      limits:
        cpu: 1000m     # 1000m = 1 CPU
        memory: 1024Mi # 1024Mi = 1 GB mem
