{{ if .Values.enabled }}

{{ $default_tango_host := printf "%s-%s" "databaseds-tango-base-" .Release.Name }}
{{ $tango_host := tpl (coalesce .Values.global.tango_host .Values.tango_host $default_tango_host | toString) . }}
{{ $dsconfig := coalesce .Values.global.dsconfig .Values.dsconfig}}
{{ $itango := coalesce .Values.global.itango .Values.itango}}
{{ $alarmhandler := coalesce .Values.global.alarmhandler .Values.alarmhandler}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "alarm-configuration-{{ template "ska-tmc-mid.name" . }}-{{ .Release.Name }}"
  namespace: {{ .Release.Namespace }}
  labels:
{{ toYaml (coalesce .Values.global.labels .Values.labels "label:none") | indent 4 }}
  annotations:
{{ toYaml (coalesce .Values.global.annotations .Values.annotations "annotations:none") | indent 4 }}
data:
  configure_alarms.py:
{{ (tpl (.Files.Glob "data/configure_alarms.py").AsConfig . ) | indent 2 }}
  alarms.json:
{{ (tpl (.Files.Glob "data/alarms.json").AsConfig . ) | indent 2 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: configure-alarm-{{ template "ska-tmc-mid.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ toYaml (coalesce .Values.global.labels .Values.labels "label:none") | indent 4 }}
  annotations:
{{ toYaml (coalesce .Values.global.annotations .Values.annotations "annotations:none") | indent 4 }}
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      volumes:
      - name: configure-alarm
        configMap:
          name: "alarm-configuration-{{ template "ska-tmc-mid.name" . }}-{{ .Release.Name }}"
      initContainers:
        - name: wait-for-devices
          image: "{{ $dsconfig.image.registry }}/{{ $dsconfig.image.image }}:{{ $dsconfig.image.tag }}"
          imagePullPolicy: {{ $dsconfig.image.pullPolicy }}
          command:
            - sh
          args:
            - -c
            - "retry --max=20 -- tango_admin --ping-device ska_mid/tm_alarmhandler/tmalarmhandler"
          env:
          - name: TANGO_HOST
            value: {{ $tango_host }}
      containers:
      - name: configure-alarm
        image: "{{ $itango.image.registry }}/{{ $itango.image.image }}:{{ $itango.image.tag }}"
        imagePullPolicy: {{ $itango.image.pullPolicy }}
        command:
          - sh
        args:
          - -c
          - "/venv/bin/python data/configure_alarms.py"
        env:
        - name: TANGO_HOST
          value: {{ $tango_host }}
        volumeMounts:
          - name: configure-alarm
            mountPath: /app/data
            readOnly: true
      restartPolicy: OnFailure
{{ end }}

