# # In/Out command constants
CMD_ASSIGN_RESOURCES = "AssignResources"
CMD_RELEASE_RESOURCES = "ReleaseResources"
CMD_CONFIGURE = "Configure"
CMD_SCAN = "Scan"
CMD_ENDSCAN = "EndScan"
CMD_ENDSB = "EndSB"
CMD_RESET = "End"
CMD_ABORT = "Abort"
CMD_RESTART = "Restart"

# #Error messages
ERR_INIT_PROP_ATTR_CN = "Error on initialising properties and attributes " \
                         "on Sdp Subarray Leaf Node Node device."
ERR_INVALID_JSON = "Invalid JSON format"
ERR_JSON_KEY_NOT_FOUND = "JSON key not found "
ERR_RELEASE_RESOURCES_CMD = "Error occured while releasing resources "
ERR_ENDSCAN_INVOKING_CMD = "Error while invoking EndScan command on SDP Subarray."
ERR_ENDSB_INVOKING_CMD = "Error while invoking EndSB command on SDP Subarray."
ERR_ABORT_INVOKING_CMD = "Error while invoking Abort command on SDP Subarray."
ERR_RESTART_INVOKING_CMD = "Error while invoking Restart command on SDP Subarray."
ERR_ASSGN_RESOURCES = "Error occurred while assigning resources to the SDP Subarray \n"
ERR_RELEASE_RESOURCES = "Error occurred while releasing resources from the Subarray \n"
ERR_CONFIGURE = "Error while invoking Configure command on SDP Subarray."
ERR_SCAN = "Error while invoking Scan command on SDP Subarray."
ERR_INVALID_JSON_CONFIG = "Invalid JSON format while invoking Configure command on SDP Subarray."
ERR_INVALID_JSON_SCAN = "Invalid JSON format while invoking Scan command on SDP Subarray."
ERR_DEVICE_NOT_IN_SCAN = "SdpSubarray is not in SCANNING state."
ERR_EXCEPT_CMD_CB = "Exception in CommandCallback: \n"
ERR_EXCEPT_RELEASE_ALL_RESOURCES_CMD_CB = "Exception in ReleaseAllResources CommandCallback: \n"
ERR_EXCEPT_CONFIGURE_CMD_CB = "Exception in Configure CommandCallback: \n"
ERR_EXCEPT_SCAN_CMD_CB = "Exception in Scan CommandCallback: \n"
ERR_EXCEPT_END_SCAN_CMD_CB = "Exception in EndScan CommandCallback: \n"
ERR_EXCEPT_END_SB_CMD_CB = "Exception in EndSB CommandCallback: \n"
ERR_EXCEPT_ABORT_CMD_CB = "Exception in Abort CommandCallback: \n"
ERR_EXCEPT_RESTART_CMD_CB = "Exception in Restart CommandCallback: \n"
ERR_DEVICE_NOT_READY = "SdpSubarray is not in ready state."
ERR_INVOKING_CMD = "Error in invoking command: "
ERR_IN_CREATE_PROXY_SDPSA = "Error in creating proxy of the SDP Subarray device."
#
# #strings
# #General strings
STR_HEALTH_STATE = "healthState of "
STR_OK = " :-> OK"
STR_DEGRADED = " :-> DEGRADED"
STR_FAILED = " :-> FAILED"
STR_UNKNOWN = " :-> UNKNOWN"
STR_HEALTH_STATE_UNKNOWN_VAL = "SDP Subarray leaf healthState event returned unknown value \n"
STR_ERR_MSG = "Error message is: "
STR_INIT_SUCCESS = "SDP Subarray Leaf Node is initialized successfully."
STR_FALSE = "False"
STR_SDPSALN_INIT_SUCCESS = "SdpSubarrayLeafNode initialized successfully."
STR_PROCESSINGBLOCKID_LIST = "processingBlockIdList"
STR_ASSIGN_RESOURCES_SUCCESS = "Resources are assigned successfully"
STR_FALSE_TAG = "False in ReleaseALL tag is not yet supported"
STR_REL_RESOURCES = "Release Resources invoked successfully on SDP Subarray."
STR_ALL_RES_NOT_REL = "All the resources are not released"
STR_LIST_RES_NOT_REL = "List of the resources that are not released:"
STR_CONFIGURE_SUCCESS = "Configure invoked successfully on SdpSubarray."
STR_ENDSCAN_SUCCESS = "EndScan invoked successfully on SdpSubarray."
STR_ENDSB_SUCCESS = "EndSB invoked successfully on SdpSubarray."
STR_CONFIG_EXEC = "Configure command execution"
STR_ABORT_SUCCESS = "Abort invoked successfully on SdpSubarray."
STR_RESTART_SUCCESS = "Restart invoked successfully on SdpSubarray."
STR_SCAN_EXEC = "Scan command execution"
STR_SCAN_SUCCESS = "Scan invoked successfully on SdpSubarray."
STR_CMD_FAILED = "SDP Subarray Leaf Node_CommandFailed"
STR_RELEASE_RES_EXEC = "ReleaseResources command execution"
STR_ASSIGN_RES_EXEC = "AssignResources command execution"
STR_ENDSCAN_EXEC = "EndScan command execution"
STR_ENDSB_EXEC = "EndSB command execution"
STR_RELEASE_RES_CMD_CALLBK = "SdpSubarrayLeafNode ReleaseAllresources Command Callback"
STR_CONFIGURE_CMD_CALLBK = "SdpSubarrayLeafNode Configure Command Callback"
STR_SCAN_CMD_CALLBK = "SdpSubarrayLeafNode Scan Command Callback"
STR_ENDSCAN_CMD_CALLBK = "SdpSubarrayLeafNode EndScan Command Callback"
STR_ENDSB_CMD_CALLBK = "SdpSubarrayLeafNode EndSB Command Callback"
STR_ABORT_CMD_CALLBK = "SdpSubarrayLeafNode Abort Command Callback"
STR_RESTART_CMD_CALLBK = "SdpSubarrayLeafNode Restart Command Callback"
STR_COMMAND = "Command :-> "
STR_INVOKE_SUCCESS = " invoked successfully."

# #PROPERTIES DEFAULT VALUES
PROP_DEF_VAL_TM_MID_SDP_SA = "mid_sdp/elt/subarray_1"

