apiVersion: v2
name: mvp-mid
description: A Helm chart for Kubernetes MVP Mid 
type: application
version: 0.1.0
appVersion: 0.1.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
- name: etcd-operator
  version: 0.11.0
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
- name: tango-base
  version: 0.1.2
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
- name: cbf-proto
  version: 0.4.0
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
- name: csp-proto
  version: 0.5.3
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
- name: sdp-prototype
  version: 0.4.0
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
- name: tmc-proto
  version: 0.1.0
  repository: file://../tmc-proto 
- name: webjive
  version: 0.1.0
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
- name: logging
  version: 0.1.0
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart