display: ":0"
xauthority: "~/.Xauthority"

enabled: true

system: SW-infrastructure
subsystem: ska-tmc-sdpsln
telescope: SKA-mid

subarray_count: 1
dishes: ["01"]

labels:
  app: ska-tmc-sdpsln

global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000
  retry:
  - "--tries=10"
  - "--sleep=5"

dsconfig:
  configuration_file: data/configuration.json
  timeout: 300s
  image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-dsconfig
      tag: 1.5.1
      pullPolicy: IfNotPresent

itango:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-itango
    tag: 9.3.5
    pullPolicy: IfNotPresent


sdpslnmid:
  image:
    registry: artefact.skao.int
    image: ska-tmc
    tag: 0.3.6
    pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 150m
    memory: 150Mi
  requests:
    cpu: 50m
    memory: 50Mi

deviceServers:
  mocks:
    enabled: false
    instances: ["01"]
    file: "data/mockdevices.yaml"

  sdpsln:
    enabled: true
    instances: ["01"]
    subarray_count: 1
    mid:
      file: "data/sdpsubarrayleafnode_mid.yaml"
      SdpSubarrayFQDN: "mid_sdp/elt/subarray_1"

nodeSelector: {}

affinity: {}

tolerations: []
