display: ":0"
xauthority: "~/.Xauthority"

enabled: true

system: TM-mid
telescope: SKA-mid
subsystem: ska-tmc-mid

labels:
  app: ska-tmc
annotations:
  app.gitlab.com/app: CI_PROJECT_PATH_SLUG
  app.gitlab.com/env: CI_ENVIRONMENT_SLUG

global:
  minikube: false
  tango_host: databaseds-tango-base-test:10000
  skatmc:
    registry: artefact.skao.int/ska-telescope
    image: ska-tmc
    tag: 0.8.3-dirty
    pullPolicy: IfNotPresent


  ##  Order of instances resolution ##
  # .Values.global.dishes & .Values.global.subarray_count
  # .Values.deviceServers.<device>.instances
  # File, data/<device>.yaml, instances

  # List the dishes, if set, then this list will be applied to instances of:
  # deviceServers.dishmaster, deviceServers.dishleafnode
  dish_devices: ["dishmaster", "dishleafnode"]
  dishes: ["01", "02", "03", "04"]

  # subarray_count, this will be expanded (1 to N inclusive) and applied to instances of:
  # deviceServers.cspsubarrayleafnode, deviceServers.sdpsubarrayleafnode, deviceServers.subarraynode
  subarray_devices:
    - "cspsubarrayleafnode"
    - "sdpsubarrayleafnode"
    - "subarraynode"
  subarray_count: 3

dsconfig:
  configuration_file: data/tmc-mid-config.json
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.1
    pullPolicy: IfNotPresent

itango:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-itango
    tag: 9.3.5
    pullPolicy: IfNotPresent

centralnodemid:
  image:
    registry: artefact.skao.int/ska-telescope
    image: ska-tmc-centralnode-mid
    tag: 0.2.9
    pullPolicy: IfNotPresent


subarraynodemid:
  image:
    registry: artefact.skao.int/ska-telescope
    image: ska-tmc-subarraynode-mid
    tag: 0.3.4
    pullPolicy: IfNotPresent

alarmhandler:
  image:
    registry: nexus.engageska-portugal.pt/tango-example
    image: tmalarmhandler
    tag: 0.1.5
    pullPolicy: IfNotPresent

# alarmhandler:
#   image:
#     registry: artefact.skao.int/ska-telescope
#     image: ska-alarmhandler
#     tag: 0.1.5
#     pullPolicy: IfNotPresent

# resources:
#   limits:
#     cpu: 300m
#     memory: 500Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi

deviceServers:
  dishmaster:
    instances: ["01", "02", "03", "04"]
    file: "data/dishmaster.yaml"
  dishleafnode:
    instances: ["01", "02", "03", "04"]
    file: "data/dishleafnode.yaml"
  cspsubarrayleafnode:
    instances: ["01", "02", "03"]
    file: "data/cspsubarrayleafnode.yaml"
  cspmasterleafnode:
    instances: ["01"]
    file: "data/cspmasterleafnode.yaml"
  sdpsubarrayleafnode:
    instances: ["01", "02", "03"]
    file: "data/sdpsubarrayleafnode.yaml"
  sdpmasterleafnode:
    instances: ["01"]
    file: "data/sdpmasterleafnode.yaml"
  subarraynode:
    instances: ["01", "02", "03"]
    file: "data/subarraynode.yaml"
  centralnode:
    instances: ["01"]
    file: "data/centralnode.yaml"
  tm-alarmhandler:
    instances: ["01"]
    file: "data/alarmhandler.yaml"
