apiVersion: v2 # for helm3. For previous helm, use v1
name: tmc-common
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application # appication or library

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 1.16.0 # This field is informational, and has no impact on chart version calculations.
# added by Snehal just to be aware
kubeVersion : 1.1 - 2.3.4
dependency:
  - name: tmc-mid
    version: 0.0.1
    repository: "/home/ubuntu/projects/tmc-prototype/charts/tmc-mid" 
