apiVersion: v2
name: ska-tmc-leafnodes
description: A subchart for ska-tmc-leafnodes deployment.
type: application
version: 0.8.14
appVersion: 0.8.14
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
maintainers:
  - name: Aditya Dange
    email: adityadange.ska@gmail.com
  - name: Snehal Nakave
    email: snehal.ska@gmail.com
  - name: Kalyani Thigale
    email: kalyanit.ska@gmail.com
dependencies:
- name: ska-tango-base
  version: 0.3.5
  repository: https://artefact.skao.int/repository/helm-internal
  condition: ska-tango-base.enabled,global.sub-system.ska-tango-base.enabled
- name: ska-tango-util
  version: 0.3.5
  repository: https://artefact.skao.int/repository/helm-internal