---

###########################################
##     PRINT STUFF
###########################################

- name: Print software_root directory
  debug: msg="rootdir = {{software_root}}"

###########################################
##     Update working directories
###########################################

# Do we want to pull on refresh_sw ???

- name: Refresh lmc-base-classes
  command: git -C {{software_root}}/lmc-base-classes pull
  tags:
    - refresh-sw-lmc-base-classes

...
