apiVersion: v2
name: tmc-mid-umbrella
description: An umbrella Helm chart for SKA-TMC-Mid deployment.
type: application
version: 0.0.2
appVersion: 1.16.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
maintainers:
  - name: Aditya Dange
    email: adityadange.ska@gmail.com
  - name: Snehal Nakave
    email: snehal.ska@gmail.com
  - name: Kalyani Thigale
    email: kalyanit.ska@gmail.com
dependencies:
- name: tango-base
  version: 0.2.23
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
- name: mid-cbf
  version: 0.1.1
  condition: mid-cbf.enabled
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
- name: mid-csp
  version: 0.1.5
  condition: mid-csp.enabled
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
- name: sdp
  version: 0.4.0
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
  condition: sdp.enabled
- name: tmc-mid
  version: 0.3.9
  repository: file://../tmc-mid
  condition: tmc-mid.enabled
- name: webjive
  version: 1.0.18
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
  condition: webjive.enabled
- name: tango-util
  version: 0.2.13
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
