
display: ":0"
xauthority: "~/.Xauthority"
minikube: true

global:
  labels:
    app: tmc-prototype
  annotations:
    app.gitlab.com/app: CI_PROJECT_PATH_SLUG
    app.gitlab.com/env: CI_ENVIRONMENT_SLUG
  tango_host: databaseds-tango-base-test:10000
  environment_variables: []
  dsconfig:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-dsconfig
      tag: 1.5.0
      pullPolicy: IfNotPresent
  itango:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-itango
      tag: 9.3.1
      pullPolicy: IfNotPresent

tmc-proto:
  dsconfig:
    configuration_file: data/tmc-mid-config.json
  deviceServers:
  - name: dishmaster1
    function: receptor-simulation
    domain: sensing
    args:
      - -c
      - "/usr/local/bin/DishMasterDS 01"
    depends_on:
      - device: sys/database/2
    image:
      registry: nexus.engageska-portugal.pt/tango-example
      image: tmcprototype
      tag: 0.2.11
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 128Mi
  - name: dishmaster2
    function: receptor-simulation
    domain: sensing
    args:
      - -c
      - "/usr/local/bin/DishMasterDS 02"
    depends_on:
      - device: sys/database/2
    image:
      registry: nexus.engageska-portugal.pt/tango-example
      image: tmcprototype
      tag: 0.2.11
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 128Mi
  - name: dishmaster3
    function: receptor-simulation
    domain: sensing
    args:
      - -c
      - "/usr/local/bin/DishMasterDS 03"
    depends_on:
      - device: sys/database/2
    image:
      registry: nexus.engageska-portugal.pt/tango-example
      image: tmcprototype
      tag: 0.2.11
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 128Mi
  - name: dishmaster4
    function: receptor-simulation
    domain: sensing
    args:
      - -c
      - "/usr/local/bin/DishMasterDS 04"
    depends_on:
      - device: sys/database/2
    image:
      registry: nexus.engageska-portugal.pt/tango-example
      image: tmcprototype
      tag: 0.2.11
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 128Mi
  - name: dishleafnode1
    function: dish-monitoring
    domain: general-monitoring
    args:
      - -c
      - "/usr/local/bin/DishLeafNodeDS 01"
    depends_on:
      - device: mid_d0001/elt/master

    image:
      registry: nexus.engageska-portugal.pt/tango-example
      image: tmcprototype
      tag: 0.2.11
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 128Mi
  - name: dishleafnode2
    function: dish-monitoring
    domain: general-monitoring
    args:
      - -c
      - "/usr/local/bin/DishLeafNodeDS 02"
    depends_on:
      - device: mid_d0001/elt/master
    image:
      registry: nexus.engageska-portugal.pt/tango-example
      image: tmcprototype
      tag: 0.2.11
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 128Mi
  - name: dishleafnode3
    function: dish-monitoring
    domain: general-monitoring
    args:
      - -c
      - "/usr/local/bin/DishLeafNodeDS 03"
    depends_on:
      - device: mid_d0001/elt/master
    image:
      registry: nexus.engageska-portugal.pt/tango-example
      image: tmcprototype
      tag: 0.2.11
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 128Mi
  - name: dishleafnode4
    function: dish-monitoring
    domain: general-monitoring
    args:
      - -c
      - "/usr/local/bin/DishLeafNodeDS 04"
    depends_on:
      - device: mid_d0001/elt/master
    image:
      registry: nexus.engageska-portugal.pt/tango-example
      image: tmcprototype
      tag: 0.2.11
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 128Mi
  - name: cspsubarrayleafnode1
    function: observation-execution
    domain: subarray
    args:
      - -c
      - "/usr/local/bin/CspSubarrayLeafNodeDS 01"
    depends_on:
      - device: mid_csp/elt/subarray_01
    image:
      registry: nexus.engageska-portugal.pt/tango-example
      image: tmcprototype
      tag: 0.2.11
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 128Mi  
  - name: cspsubarrayleafnode2
    function: observation-execution
    domain: subarray
    args:
      - -c
      - "/usr/local/bin/CspSubarrayLeafNodeDS 02"
    depends_on:
      - device: mid_csp/elt/subarray_02
    image:
      registry: nexus.engageska-portugal.pt/tango-example
      image: tmcprototype
      tag: 0.2.11
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 128Mi  
  - name: cspsubarrayleafnode3
    function: observation-execution
    domain: subarray
    args:
      - -c
      - "/usr/local/bin/CspSubarrayLeafNodeDS 03"
    depends_on:
      - device: mid_csp/elt/subarray_03
    image:
      registry: nexus.engageska-portugal.pt/tango-example
      image: tmcprototype
      tag: 0.2.11
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 128Mi  
  - name: cspmasterleafnode
    function: csp-monitoring
    domain: general-monitoring
    args:
      - -c
      - "/usr/local/bin/CspMasterLeafNodeDS 01"
    depends_on:
      - device: mid_csp/elt/master
    image:
      registry: nexus.engageska-portugal.pt/tango-example
      image: tmcprototype
      tag: 0.2.11
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 128Mi  
  - name: sdpsubarrayleafnode1
    function: observation-execution
    domain: subarray
    args:
      - -c
      - "/usr/local/bin/SdpSubarrayLeafNodeDS 01"
    depends_on:
      - device: mid_sdp/elt/subarray_1
    image:
      registry: nexus.engageska-portugal.pt/tango-example
      image: tmcprototype
      tag: 0.2.11
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 128Mi  
  - name: sdpsubarrayleafnode2
    function: observation-execution
    domain: subarray
    args:
      - -c
      - "/usr/local/bin/SdpSubarrayLeafNodeDS 02"
    depends_on:
      - device: mid_sdp/elt/subarray_2
    image:
      registry: nexus.engageska-portugal.pt/tango-example
      image: tmcprototype
      tag: 0.2.11
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 128Mi  
  - name: sdpsubarrayleafnode3
    function: observation-execution
    domain: subarray
    args:
      - -c
      - "/usr/local/bin/SdpSubarrayLeafNodeDS 03"
    depends_on:
      - device: mid_sdp/elt/subarray_3
    image:
      registry: nexus.engageska-portugal.pt/tango-example
      image: tmcprototype
      tag: 0.2.11
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 128Mi  
  - name: sdpmasterleafnode
    function: observation-execution
    domain: subarray
    args:
      - -c
      - "/usr/local/bin/SdpMasterLeafNodeDS 01"
    depends_on:
      - device: mid_sdp/elt/master
    image:
      registry: nexus.engageska-portugal.pt/tango-example
      image: tmcprototype
      tag: 0.2.11
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 128Mi  
  - name: subarraynode1
    function: observation-execution
    domain: subarray
    args:
      - -c
      - "/usr/local/bin/SubarrayNodeDS sa1"
    depends_on:
      - device: ska_mid/tm_leaf_node/d0001
      - device: ska_mid/tm_leaf_node/d0002
      - device: ska_mid/tm_leaf_node/d0003
      - device: ska_mid/tm_leaf_node/d0004
      - device: ska_mid/tm_leaf_node/csp_subarray01
      - device: ska_mid/tm_leaf_node/sdp_subarray01
    image:
      registry: nexus.engageska-portugal.pt/tango-example
      image: tmcprototype
      tag: 0.2.11
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 128Mi  
  - name: subarraynode2
    function: observation-execution
    domain: subarray
    args:
      - -c
      - "/usr/local/bin/SubarrayNodeDS sa2"
    depends_on:
      - device: ska_mid/tm_leaf_node/d0001
      - device: ska_mid/tm_leaf_node/d0002
      - device: ska_mid/tm_leaf_node/d0003
      - device: ska_mid/tm_leaf_node/d0004
      - device: ska_mid/tm_leaf_node/csp_subarray02
      - device: ska_mid/tm_leaf_node/sdp_subarray02
    image:
      registry: nexus.engageska-portugal.pt/tango-example
      image: tmcprototype
      tag: 0.2.11
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 128Mi  
  - name: subarraynode3
    function: observation-execution
    domain: subarray
    args:
      - -c
      - "/usr/local/bin/SubarrayNodeDS sa3"
    depends_on:
      - device: ska_mid/tm_leaf_node/d0001
      - device: ska_mid/tm_leaf_node/d0002
      - device: ska_mid/tm_leaf_node/d0003
      - device: ska_mid/tm_leaf_node/d0004
      - device: ska_mid/tm_leaf_node/csp_subarray03
      - device: ska_mid/tm_leaf_node/sdp_subarray03
    image:
      registry: nexus.engageska-portugal.pt/tango-example
      image: tmcprototype
      tag: 0.2.11
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 128Mi  
  - name: centralnode
    function: telescope-monitoring
    domain: general-monitoring
    args:
      - -c
      - "/usr/local/bin/CentralNodeDS 01"
    depends_on:
      - device: ska_mid/tm_leaf_node/csp_master
      - device: ska_mid/tm_leaf_node/sdp_master
      - device: ska_mid/tm_subarray_node/1
      - device: ska_mid/tm_subarray_node/2
      - device: ska_mid/tm_subarray_node/3
    image:
      registry: nexus.engageska-portugal.pt/tango-example
      image: tmcprototype
      tag: 0.2.11
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 128Mi
  - name: tm-alarmhandler
    function: alarm-management
    domain: general-monitoring
    args:
      - -c
      - "./app/alarmhandler-srv 01"
    depends_on:
      - device: sys/database/2
    image:
      registry: nexus.engageska-portugal.pt/tango-example
      image: tmalarmhandler
      tag: latest
      pullPolicy: Always
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 128Mi

webjive:
  ingress:
    enabled: true
    nginx: false
    hostname: integration.engageska-portugal.pt

etcd-operator:
  deployments:
    backupOperator: false
    restoreOperator: false

# Need to identify the dependencies from lower level devices which are common and referred in TMC as well.
# The same dependencies should be only referred in one chart at a time. 
# This is handled by making the enable : true/false the dependency.
# mid-csp:
#   tango-base:
#     enabled: false

# sdp:
#   etcd:
#     enbaled: false
#   tango-base:
#     enabled: false

