display: ":0"
xauthority: "~/.Xauthority"

global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000
  sub-system:
    tango-base:
      enabled: false

# Set minikube=true when deploying on minikube
webjive:
  minikube: false

etcd-operator:
  deployments:
    backupOperator: false
    restoreOperator: false

# Need to identify the dependencies from lower level devices which are common and referred in TMC as well.
# The same dependencies should be only referred in one chart at a time. 
# This is handled by making the enable : true/false the dependency.

mid-csp:
  enabled: true
      
mid-cbf:
  enabled: true

sdp:
  tango-base:
    enabled: false
  lmc:
    enabled: true



