display: ":0"
xauthority: "~/.Xauthority"
minikube: true

global:
  labels:
    app: tmc-prototype
  annotations:
    app.gitlab.com/app: CI_PROJECT_PATH_SLUG
    app.gitlab.com/env: CI_ENVIRONMENT_SLUG
  tango_host: databaseds-tango-base-test:10000
  environment_variables: []
  dsconfig:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-dsconfig
      tag: 1.5.0
      pullPolicy: IfNotPresent
  itango:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-itango
      tag: 9.3.1
      pullPolicy: IfNotPresent
  sub-system:
    tango-base:
      enabled: false

# Set minikube=true when deploying on minikube
webjive:
  minikube: false

etcd-operator:
  deployments:
    backupOperator: false
    restoreOperator: false

# Need to identify the dependencies from lower level devices which are common and referred in TMC as well.
# The same dependencies should be only referred in one chart at a time. 
# This is handled by making the enable : true/false the dependency.

csp-proto:      
  csplmc:
     enabled: true
cbf-proto:
  midcbfmcs:
     enabled: true

# csp-proto:
#   tango-base:
#     enabled: false

# cbf-proto:
#   tango-base:
#     enabled: false

sdp-prototype:
  # tango-base:
  #   tangodb:
  #     enabled: false
  #   databaseds:
  #     enabled: false

  # ds config
  dsconfig:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-dsconfig
      tag: 1.2.5.1
      pullPolicy: IfNotPresent

  # Processing controller
  processing_controller:
    image: nexus.engageska-portugal.pt/sdp-prototype/processing-controller
    version: 0.6.0
    replicas: 1
    resources: {}
    imagePullPolicy: IfNotPresent
    workflows:
      url: https://gitlab.com/ska-telescope/sdp-prototype/-/raw/master/src/workflows/workflows.json
      refresh: 300

  # Tango devices
  tangods:
    component: subarray-controller
    subsystem: execution-control
    function: sdp-monitoring-and-control
    domain: subarray
    master:
      image: nexus.engageska-portugal.pt/sdp-prototype/tangods_sdp_master
      version: 0.3.3
      imagePullPolicy: IfNotPresent
    subarray:
      image: nexus.engageska-portugal.pt/sdp-prototype/tangods_sdp_subarray
      version: 0.11.0
      imagePullPolicy: IfNotPresent


