display: ":0"
xauthority: "~/.Xauthority"

global:
  retry: 
  - "--sleep=1"
  - "--tries=100"
  sub-system:
    tango-util:
      enabled: false
    tango-base:
      enabled: false
    webjive:
      enabled: true
  tango_host: databaseds-tango-base-test:10000
  dsconfig:
    timeout: 300s
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-dsconfig
      tag: 1.5.0
      pullPolicy: IfNotPresent
  itango:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-itango
      tag: 9.3.1
      pullPolicy: IfNotPresent

tango-base:
  enabled: true
  vnc:
    replicas: 1
    enabled: true
  tangorest:
    enabled: true
    replicas: 1
  tangodb:
    use_pv: false

webjive:
  enabled: true
  minikube: true
  ingress:
    enabled: true
    nginx: true
    hostname: k8s.stfc.skao.int
  tangogql:
    replicas: 3
    # resources:
    #   requests:
    #     cpu: 600m     # 600m = 0.6 CPU
    #     memory: 512Mi # 512Mi = 0.5 GB mem
    #   limits:
    #     cpu: 1000m     # 1000m = 1 CPU
    #     memory: 1024Mi # 1024Mi = 1 GB mem

mid-cbf:
  enabled: true

## mid-csp
mid-csp:
  enabled: true

## sdp
sdp:
  enabled: true
  lmc:
    prefix: mid
    nsubarray: 3
  tango-base:
    enabled: false

## tm
tmc-mid:
  enabled: true

# global:
#   minikube: true
#   tango_host: databaseds-tango-base-test:10000
#   sub-system:
#     tango-base:
#       enabled: false

# # Set minikube=true when deploying on minikube
# webjive:
#   minikube: true

# etcd-operator:
#   deployments:
#     backupOperator: false
#     restoreOperator: false

# # Need to identify the dependencies from lower level devices which are common and referred in TMC as well.
# # The same dependencies should be only referred in one chart at a time. 
# # This is handled by making the enable : true/false the dependency.

# mid-csp:
#   enabled: true
      
# mid-cbf:
#   enabled: true

# sdp:
#   tango-base:
#     enabled: false
#   lmc:
#     enabled: true



