
display: ":0"
xauthority: "~/.Xauthority"
minikube: true

global:
  system: TM-mid
  telescope: SKA-mid
  dsconfig_file: data/tmc-mid-config.json

tango-base:
  vnc:
    enabled: true
  tangorest:
    enabled: true
  tangotest:
    enabled: true
  ingress:
    enabled: true
  tangodb:
    use_pv: false

logging:
  elastic:
    enabled: false
  fluentd:
    enabled: false
  kibana:
    enabled: false
  tests:
    enabled: false

webjive:
  ingress:
    enabled: true
    nginx: false
    hostname: integration.engageska-portugal.pt

etcd-operator:
  deployments:
    backupOperator: true
    restoreOperator: true