display: ":0"
xauthority: "~/.Xauthority"
minikube: true

global:
  labels:
    app: tmc-prototype
  annotations:
    app.gitlab.com/app: CI_PROJECT_PATH_SLUG
    app.gitlab.com/env: CI_ENVIRONMENT_SLUG
  tango_host: databaseds-tango-base-test:10000
  environment_variables: []
  dsconfig:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-dsconfig
      tag: 1.5.0
      pullPolicy: IfNotPresent
  itango:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-itango
      tag: 9.3.1
      pullPolicy: IfNotPresent
  sub-system:
    tango-base:
      enabled: false
    webjive:
      enabled: false

# webjive:
#   ingress:
#     enabled: true
#     nginx: false
#     hostname: integration.engageska-portugal.pt

etcd-operator:
  deployments:
    backupOperator: false
    restoreOperator: false

# Need to identify the dependencies from lower level devices which are common and referred in TMC as well.
# The same dependencies should be only referred in one chart at a time. 
# This is handled by making the enable : true/false the dependency.

# mid-csp:
#   tango-base:
#     enabled: false

# sdp:
#   etcd:
#     enbaled: false
#   tango-base:
#     enabled: false
