display: ":0"
xauthority: "~/.Xauthority"

global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000
  sub-system:
    tango-base:
      enabled: false

# Set minikube=true when deploying on minikube
webjive:
  minikube: false

etcd-operator:
  deployments:
    backupOperator: false
    restoreOperator: false

# Need to identify the dependencies from lower level devices which are common and referred in TMC as well.
# The same dependencies should be only referred in one chart at a time. 
# This is handled by making the enable : true/false the dependency.

mid-csp:
  enabled: true
      
mid-cbf:
  enabled: true

# sdp-prototype:
#   # Feature toggles
#   feature:
#     # Tango devices connect to configuration DB?
#     config-db: 1
#     # # Old receive addresses behaviour?
#     # receive-addresses-hack: 0
    
#   helm_deploy:
#     image: nexus.engageska-portugal.pt/sdp-prototype/helm-deploy
#     version: 0.5.1
#     imagePullPolicy: IfNotPresent
#     replicas: 1
#     namespace: sdp
#     chart_repo:
#       url: https://gitlab.com/ska-telescope/sdp-prototype.git
#       ref: master
#       path: src/helm_deploy/charts
#       refresh: 300
#   # Configuration database
#   etcd:
#     version: "3.3"
#     replicas: 1
#   # ds config
#   dsconfig:
#     image:
#       registry: nexus.engageska-portugal.pt/ska-docker
#       image: tango-dsconfig
#       tag: 1.2.5.1
#       pullPolicy: IfNotPresent

#   # Processing controller
#   processing_controller:
#     image: nexus.engageska-portugal.pt/sdp-prototype/processing-controller
#     version: 0.6.0
#     replicas: 1
#     resources: {}
#     imagePullPolicy: IfNotPresent
#     workflows:
#       url: https://gitlab.com/ska-telescope/sdp-prototype/-/raw/master/src/workflows/workflows.json
#       refresh: 300

#   # Tango devices
#   tangods:
#     master:
#       image: nexus.engageska-portugal.pt/sdp-prototype/tangods_sdp_master
#       version: 0.3.3
#       imagePullPolicy: IfNotPresent
#     subarray:
#       image: nexus.engageska-portugal.pt/sdp-prototype/tangods_sdp_subarray
#       version: 0.11.0
#       imagePullPolicy: IfNotPresent
#   # Console
#   console:
#     image: nexus.engageska-portugal.pt/sdp-prototype/console
#     version: 0.2.0
#     imagePullPolicy: IfNotPresent
#     replicas: 1
#     enabled: true

sdp:
  tango-base:
    enabled: false
  lmc:
    enabled: true



