display: ":0"
xauthority: "~/.Xauthority"

global:
  retry: 
  - "--sleep=1"
  - "--tries=100"
  sub-system:
    tango-util:
      enabled: false
    ska-tango-base:
      enabled: false
    tango-base:
      enabled: false
    webjive:
      enabled: true
  tango_host: databaseds-tango-base-test:10000
  dsconfig:
    timeout: 300s
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-dsconfig
      tag: 1.5.0
      pullPolicy: IfNotPresent
  itango:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-itango
      tag: 9.3.1
      pullPolicy: IfNotPresent

ska-tango-base:
  vnc:
    replicas: 1
    enabled: true
  tangorest:
    enabled: true
    replicas: 1
  tangodb:
    use_pv: false

webjive:
  enabled: false
  minikube: false
  ingress:
    enabled: true
    nginx: true
  tangogql:
    replicas: 3
    # resources:
    #   requests:
    #     cpu: 600m     # 600m = 0.6 CPU
    #     memory: 512Mi # 512Mi = 0.5 GB mem
    #   limits:
    #     cpu: 1000m     # 1000m = 1 CPU
    #     memory: 1024Mi # 1024Mi = 1 GB mem

ska-mid-cbf:
  enabled: true

# mid-cbf:
#   enabled: false

ska-csp-lmc-mid:
  enabled: true

## mid-csp
# mid-csp:
#   enabled: false

## sdp
sdp:
  enabled: true
  lmc:
    prefix: mid
    nsubarray: 3
  tango-base:
    enabled: false

ska-tmc-mid:
  enabled: true

## tm
# tmc-mid:
#   enabled: false
