apiVersion: v2
name: tmc-mid
description: A Helm chart for TMC-Mid deployment
type: application
version: 0.0.2
appVersion: 1.16.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png