display: ":0"
xauthority: "~/.Xauthority"
enabled: true

system: TM-low
telescope: SKA-low
subsystem: ska-tmc-low

labels:
  app: ska-tmc
annotations:
  app.gitlab.com/app: CI_PROJECT_PATH_SLUG
  app.gitlab.com/env: CI_ENVIRONMENT_SLUG

global:
  minikube: false
  tango_host: databaseds-tango-base-test:10000
  skatmc:
    registry: artefact.skao.int/ska-telescope
    image: ska-tmc
    tag: 0.8.2
    pullPolicy: IfNotPresent

dsconfig:
  configuration_file: data/tmc-low-config.json
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.0
    pullPolicy: IfNotPresent

itango:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-itango
    tag: 9.3.1
    pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 128Mi

deviceServers:
- name: subarraynode1
  function: observation-execution
  domain: subarray
  command: "/usr/local/bin/SubarrayNodeLowDS "
  instances: ["sa1"]
  depends_on:
    - device: ska_low/tm_leaf_node/mccs_subarray01
  image:
    registry: "{{.Values.global.skatmc.registry}}"
    image: "{{.Values.global.skatmc.image}}"
    tag: "{{.Values.global.skatmc.tag}}"
    pullPolicy: "{{.Values.global.skatmc.pullPolicy}}"
- name: centralnode
  function: telescope-monitoring
  domain: general-monitoring
  command: "/usr/local/bin/CentralNodeLowDS"
  instances: ["01"]
  depends_on:
    - device: ska_low/tm_subarray_node/1
    - device: ska_low/tm_leaf_node/mccs_master
  image:
    registry: "{{.Values.global.skatmc.registry}}"
    image: "{{.Values.global.skatmc.image}}"
    tag: "{{.Values.global.skatmc.tag}}"
    pullPolicy: "{{.Values.global.skatmc.pullPolicy}}"
- name: mccssmasterleafnode
  function: observation-execution
  domain: general-monitoring
  command: "/usr/local/bin/MccsMasterLeafNodeDS"
  instances: ["01"]
  depends_on:
    - device: low-mccs/control/control
  image:
    registry: "{{.Values.global.skatmc.registry}}"
    image: "{{.Values.global.skatmc.image}}"
    tag: "{{.Values.global.skatmc.tag}}"
    pullPolicy: "{{.Values.global.skatmc.pullPolicy}}"
- name: mccssubarrayleafnode1
  function: observation-execution
  domain: subarray
  command: "/usr/local/bin/MccsSubarrayLeafNodeDS"
  instances: ["01"]
  depends_on:
    - device: low-mccs/subarray/01
  image:
    registry: "{{.Values.global.skatmc.registry}}"
    image: "{{.Values.global.skatmc.image}}"
    tag: "{{.Values.global.skatmc.tag}}"
    pullPolicy: "{{.Values.global.skatmc.pullPolicy}}"

