""" Python file containing String Variables for CSP Master Leaf Node"""

# Events
EVT_CBF_HEALTH = "cspCbfHealthState"
EVT_PSS_HEALTH = "cspPssHealthState"
EVT_PST_HEALTH = "cspPstHealthState"

#In/out commands
CMD_ON = "On"
CMD_OFF = "Off"
CMD_STANDBY = "Standby"

# String constants
STR_INIT_SUCCESS = "CSP Master Leaf Node is initialized successfully."
STR_CSP_CBF_HEALTH_OK = "CSP CBF health is OK."
STR_CSP_CBF_HEALTH_DEGRADED = "CSP CBF health is DEGRADED."
STR_CSP_CBF_HEALTH_FAILED = "CSP CBF health is FAILED."
STR_CSP_CBF_HEALTH_UNKNOWN = "CSP CBF health is UNKNOWN."
STR_CSP_PSS_HEALTH_OK = "CSP PSS health is OK."
STR_CSP_PSS_HEALTH_DEGRADED = "CSP PSS health is DEGRADED."
STR_CSP_PSS_HEALTH_FAILED = "CSP PSS health is FAILED."
STR_CSP_PSS_HEALTH_UNKNOWN = "CSP PSS health is UNKNOWN."
STR_CSP_PST_HEALTH_OK = "CSP PST health is OK."
STR_CSP_PST_HEALTH_DEGRADED = "CSP PST health is DEGRADED."
STR_CSP_PST_HEALTH_FAILED = "CSP PST health is FAILED."
STR_CSP_PST_HEALTH_UNKNOWN = "CSP PST health is UNKNOWN."
STR_ON_CMD_ISSUED = "ON command invoked successfully from CSP Master leaf node."
STR_STANDBY_CMD_ISSUED = "StandByTelescope command invoked successfully from CSP Master leaf node."
STR_OFF_CMD_ISSUED = "OFF command invoked successfully from CSP Master leaf node."
STR_COMMAND = "Command :-> "
STR_INVOKE_SUCCESS = "Command invoked successfully."
STR_SETTING_CB_MODEL = "Setting CallBack Model as :-> "
STR_CSP_INIT_LEAF_NODE = "Initializing CSP Master Leaf Node ...."
STR_CSPMASTER_FQDN = "CspMasterFQDN :-> "
STR_DEV_ALARM = "The device is in ALARM state."
STR_CMD_FAILED = "CspMasterLeafNode_Commandfailed"
STR_ON_EXEC = "On command execution"
STR_OFF_EXEC = "Off command execution"
STR_STANDBY_EXEC = "Standby command execution"

# Error messages
ERR_IN_CREATE_PROXY = "Error in creating proxy of the device "
ERR_ON_SUBS_CSP_CBF_HEALTH = "Error in subscribing CspCbfHealth attribute "
ERR_ON_SUBS_CSP_PSS_HEALTH = "Error in subscribing CspPssHealth attribute "
ERR_ON_SUBS_CSP_PST_HEALTH = "Error in subscribing CspPstHealth attribute "
ERR_SUBS_CSP_MASTER_LEAF_ATTR = "Exception occurred while subscribing to Csp Master attribute"
ERR_CSP_MASTER_LEAF_INIT = "Error occured in Csp Master Leaf Node initialization "
ERR_INVOKING_CMD = "Error in invoking command: "
ERR_EXE_ON_CMD = "Error in executing On command"
ERR_EXE_OFF_CMD = "Error in executing Off command"
ERR_EXE_STANDBY_CMD = "Error in executing Standby command"
ERR_DEVFAILED_MSG = "This is error message for devfailed"
