#!/bin/sh
python3 -c "import tango; print(tango.__version__)"

echo "========================= Starting Dish Master 1 ========================="
python3 ./DishMaster/DishMaster/DishMaster.py 01 &
python3 ./DishMaster/DishMaster/DishMaster.py 02 &
python3 ./DishMaster/DishMaster/DishMaster.py 03 &
python3 ./DishMaster/DishMaster/DishMaster.py 04 &
sleep 1

echo "========================= Starting Dish Leaf Node 1 ========================="
python3 ./DishLeafNode/DishLeafNode/DishLeafNode.py 01 &
python3 ./DishLeafNode/DishLeafNode/DishLeafNode.py 02 &
python3 ./DishLeafNode/DishLeafNode/DishLeafNode.py 03 &
python3 ./DishLeafNode/DishLeafNode/DishLeafNode.py 04 &
sleep 1

echo "========================= Starting CSP Master Leaf Node ========================="
python3 ./CspMasterLeafNode/CspMasterLeafNode/CspMasterLeafNode.py 01 &
sleep 1

echo "========================= Starting CSP Subarray ========================="
python3 ./CspSubarray/CspSubarray/CspSubarray.py 01 &
sleep 1

echo "========================= Starting CSP Subarray Leaf Node ========================="
python3 ./CspSubarrayLeafNode/CspSubarrayLeafNode/CspSubarrayLeafNode.py 01 &
sleep 1

echo "========================= Starting SDP Subarray ========================="
python3 ./SdpSubarray/SdpSubarray/SdpSubarray.py 01 &
sleep 1

echo "========================= Starting SDP Subarray Leaf Node ========================="
python3 ./SdpSubarrayLeafNode/SdpSubarrayLeafNode/SdpSubarrayLeafNode.py 01 &
sleep 1

echo "========================= Starting SDP Master ========================="
python3 ./SdpMaster/SdpMaster/SdpMaster.py 01 &
sleep 1

echo "========================= Starting SDP Master Leaf Node ========================="
python3 ./SdpMasterLeafNode/SdpMasterLeafNode/SdpMasterLeafNode.py 01 &
sleep 1

echo "========================= Starting Subarray Node 1 ========================="
python3 ./SubarrayNode/SubarrayNode/SubarrayNode.py sa1 &

echo "========================= Starting Subarray Node 2 ========================="
python3 ./SubarrayNode/SubarrayNode/SubarrayNode.py sa2 &
sleep 1

echo "========================= Starting Central Node ========================="
python3 ./CentralNode/CentralNode/CentralNode.py 01 &
sleep 1
