#!/bin/sh
python -c "import tango; print(tango.__version__)"

echo "========================= Stopping Central Node ========================="
pkill -9 -f ./CentralNode/CentralNode/CentralNode.py &
sleep 1

echo "========================= Stopping Subarray Nodes ========================="
pkill -9 -f ./SubarrayNode/SubarrayNode/SubarrayNode.py &
sleep 1

echo "========================= Stopping Dish Leaf Nodes ========================="
pkill -9 -f ./DishLeafNode/DishLeafNode/DishLeafNode.py &
sleep 1

echo "========================= Stopping Dish Masters ========================="
pkill -9 -f ./DishMaster/DishMaster/DishMaster.py &
sleep 1

